export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT= "LOGOUT";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const ERROR = "ERROR";
export const TOKEN_CHECK = "TOKEN_CHECK";
export const GET_ADMIN = "GET_ADMIN";
export const GET_ADMIN_FAILED = "GET_ADMIN_FAILED";

//admin operation
export const CREATE_COLLECTION = "CREATE_COLLECTION";
export const CREATE_COLLECTION_FAILED = "CREATE_COLLECTION_FAILED"
export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_COURSE_LIST_FAILED = "GET_COURSE_LIST_FAILED";
export const GET_COLLECTION = "GET_COLLECTION";
export const GET_COLLECTION_FAILED = "GET_COLLECTION_FAILED";
export const GET_COLLECTION_DATA = "GET_COLLECTION_DATA";
export const GET_COLLECTION_DATA_FAILED = "GET_COLLECTION_DATA_FAILED";

export const DISPLAY_COURSE_DATA = "DISPLAY_COURSE_DATA";
export const DISPLAY_SEARCH_DATA = "DISPLAY_SEARCH_DATA"
export const DISPLAY_SEARCH_DATA_FAILED = "DISPLAY_SEARCH_DATA_FAILED"

export const SHOW_EDIT_DATA = "SHOW_EDIT_DATA " 